name: padelshooter3a1
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0+2

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  url_launcher: ^6.3.0
  collection: ^1.18.0
  flutter_blue_plus: ^1.32.8
  get: ^4.6.6
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  path_provider: ^2.1.3
  share_plus: ^9.0.0
  file_picker: ^8.0.6
  cross_file: ^0.3.4+1
  http: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_translation: ^0.20.0
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/lang/en.json
    - assets/lang/es.json
    - assets/lang/fr.json
    - assets/lang/zh.json
    - assets/lang/pt.json
    - assets/lang/pl.json
    - assets/lang/fi.json
    - assets/lang/sv.json
    - assets/lang/it.json
    - assets/lang/de.json
    - assets/lang/ja.json
    - assets/lang/ar.json
    - assets/lang/lv.json
    - assets/lang/nl.json
    - assets/images/bluetooth-icon.png
    - assets/images/bluetooth-icon-greenbg.png
    - assets/images/Padelbaan_full.png
    - assets/images/Padelbaan_full_green.png
    - assets/images/PS3A-black_transp.png
    - assets/images/background_app.jpg
